parameters:
    database_driver:   pdo_mysql
    database_host:     us-cdbr-east-03.cleardb.com
    database_port:     ~
    database_name:     heroku_3b7a8a80031a434
    database_user:     b445f45c8cd759
    database_password: fdb3b817

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
